---
resolver: lts-21.25

extra-deps:
  - git: https://github.com/xmonad/xmonad
    commit: b1d9884d2d310b4d1287b52534777dfe402acda8
  - git: https://github.com/xmonad/xmonad-contrib
    commit: 0dcecb41c57d0ea6ac177ff16511f0db0eb703b8
