---
resolver: lts-23.9

extra-deps:
  - git: https://github.com/xmonad/xmonad
    commit: 07d95ad8fc395866200b4587aca8b4db50aa20bd
  - git: https://github.com/xmonad/xmonad-contrib
    commit: 4496b4f2d54b31dcf68fb5e1ad545b9afbc3dfcd
